apiVersion: apps/v1
kind: Deployment 
metadata:
  name: adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template: 
    metadata: 
      labels:
        app: adservice

    spec:  
      containers:
      - name: adservice-pod
        image: adservice
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        - name: DISABLE_PROFILER
          value: "1"
        - name: ENABLE_TRACING
          value: "1"
        - name: OTEL_SERVICE_NAME
          value: "adservice"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.microservices.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=microservices,deployment.environment=production"
      imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata: 
  name: adservice-service
spec:
  selector:
    app: adservice
  ports:
    - protocol: TCP
      port: 9555
      targetPort: 9555 